[lib]
proc-macro = true

[package]
name = "fso_tables_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0.66", features = ["full"] }
quote = "1.0.36"
proc-macro2 = "1.0.85"
regex = "1.10.5"
